packages:
  - apps/*
  - packages/*

catalog:
  '@tsconfig/node24': 24.0.4
  '@types/bun': 1.3.8
  '@types/node': 24.10.12
  '@typescript/native-preview': 7.0.0-dev.20260211.1
  oxfmt: 0.31.0
  oxlint: 1.46.0
  oxlint-tsgolint: 0.12.0
  typescript: 5.9.3
  unplugin-dts: 1.0.0-beta.6
  vite: 8.0.0-beta.13
  zod: 4.3.6

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver
