packages:
  - examples/*
  - packages/*

allowBuilds:
  esbuild: true
  lefthook: true
  unrs-resolver: true

catalog:
  '@tsconfig/node24': 24.0.5
  '@types/bun': 1.4.0
  oxfmt: 0.64.0
  oxlint: 1.80.0
  oxlint-tsgolint: 7.0.2001
  typescript: 7.0.2
  vite: 8.2.2
  zod: 4.4.3

minimumReleaseAge: 4320
