packages:
  - apps/*
  - packages/*

catalog:
  '@tsconfig/node24': 24.0.4
  '@types/bun': 1.3.8
  '@types/node': 24.10.10
  '@typescript/native-preview': 7.0.0-dev.20260203.1
  oxfmt: 0.28.0
  oxlint: 1.43.0
  oxlint-tsgolint: 0.11.4
  typescript: 5.9.3
  unplugin-dts: 1.0.0-beta.6
  vite: 8.0.0-beta.12
  zod: 3.25.67

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver
